routes/web.php
<?php

use App\Http\Controllers\API;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\ReportUserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use Database\Seeders\CreatePermissionSeeder;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect("login");
});

Route::get('upgrade-to-v3-4-0', function () {
    try {
        \Artisan::call('migrate', [
            '--path'  => '/database/migrations/2020_10_19_133700_move_all_existing_devices_to_new_table.php',
            '--force' => true,
        ]);

        return 'You are successfully migrated to v3.4.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Route::get('/upgrade-to-v4-3-0', function () {
    try {
        Artisan::call('db:seed', ['--class' => 'CreatePermissionSeeder']);

        return 'You are successfully seeded to v4.3.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Route::get('upgrade-to-v5-0-0', function () {
    try {
        \Artisan::call('migrate', [
            '--path'  => '/database/migrations/2021_07_12_000000_add_uuid_to_failed_jobs_table.php',
            '--force' => true,
        ]);

        return 'You are successfully migrated to v5.0.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Auth::routes();
Route::get('activate', [AuthController::class, 'verifyAccount']);

Route::get('/home', [HomeController::class, 'index']);
Route::post('update-language', [UserController::class, 'updateLanguage'])->middleware('auth');
Route::group(['middleware' => ['user.activated', 'auth']], function () {
    //view routes
    Route::get('/conversations',
        [ChatController::class, 'index'])->name('conversations')->middleware('permission:manage_conversations');
    Route::get('profile', [UserController::class, 'getProfile']);
    Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

    //get all user list for chat
    Route::get('users-list', [API\UserAPIController::class, 'getUsersList']);
    Route::get('get-users', [API\UserAPIController::class, 'getUsers']);
    Route::delete('remove-profile-image', [API\UserAPIController::class, 'removeProfileImage']);
    /** Change password */
    Route::post('change-password', [API\UserAPIController::class, 'changePassword']);
    Route::get('conversations/{ownerId}/archive-chat', [API\UserAPIController::class, 'archiveChat']);

    Route::get('get-profile', [API\UserAPIController::class, 'getProfile']);
    Route::post('profile', [API\UserAPIController::class, 'updateProfile'])->name('update.profile');
    Route::post('update-last-seen', [API\UserAPIController::class, 'updateLastSeen']);

    Route::post('send-message',
        [API\ChatAPIController::class, 'sendMessage'])->name('conversations.store')->middleware('sendMessage');
    Route::get('users/{id}/conversation', [API\UserAPIController::class, 'getConversation']);
    Route::get('conversations-list', [API\ChatAPIController::class, 'getLatestConversations']);
    Route::get('archive-conversations', [API\ChatAPIController::class, 'getArchiveConversations']);
    Route::post('read-message', [API\ChatAPIController::class, 'updateConversationStatus']);
    Route::post('file-upload', [API\ChatAPIController::class, 'addAttachment'])->name('file-upload');
    Route::post('image-upload', [API\ChatAPIController::class, 'imageUpload'])->name('image-upload');
    Route::get('conversations/{userId}/delete', [API\ChatAPIController::class, 'deleteConversation']);
    Route::post('conversations/message/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessage']);
    Route::post('conversations/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessageForEveryone']);
    Route::get('/conversations/{conversation}', [API\ChatAPIController::class, 'show']);
    Route::post('send-chat-request', [API\ChatAPIController::class, 'sendChatRequest'])->name('send-chat-request');
    Route::post('accept-chat-request',
        [API\ChatAPIController::class, 'acceptChatRequest'])->name('accept-chat-request');
    Route::post('decline-chat-request',
        [API\ChatAPIController::class, 'declineChatRequest'])->name('decline-chat-request');

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification']);

    /** BLock-Unblock User */
    Route::put('users/{user}/block-unblock', [API\BlockUserAPIController::class, 'blockUnblockUser']);
    Route::get('blocked-users', [API\BlockUserAPIController::class, 'blockedUsers']);

    /** My Contacts */
    Route::get('my-contacts', [API\UserAPIController::class, 'myContacts'])->name('my-contacts');

    /** Groups API */
    Route::post('groups', [API\GroupAPIController::class, 'create']);
    Route::post('groups/{group}', [API\GroupAPIController::class, 'update']);
    Route::get('groups', [API\GroupAPIController::class, 'index']);
    Route::get('groups/{group}', [API\GroupAPIController::class, 'show']);
    Route::put('groups/{group}/add-members', [API\GroupAPIController::class, 'addMembers']);
    Route::delete('groups/{group}/members/{user}', [API\GroupAPIController::class, 'removeMemberFromGroup']);
    Route::delete('groups/{group}/leave', [API\GroupAPIController::class, 'leaveGroup']);
    Route::delete('groups/{group}/remove', [API\GroupAPIController::class, 'removeGroup']);
    Route::put('groups/{group}/members/{user}/make-admin', [API\GroupAPIController::class, 'makeAdmin']);
    Route::put('groups/{group}/members/{user}/dismiss-as-admin', [API\GroupAPIController::class, 'dismissAsAdmin']);
    Route::get('users-blocked-by-me', [API\BlockUserAPIController::class, 'blockUsersByMe']);

    Route::get('notification/{notification}/read', [API\NotificationController::class, 'readNotification']);
    Route::get('notification/read-all', [API\NotificationController::class, 'readAllNotification']);

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification']);
    Route::put('update-player-id', [API\UserAPIController::class, 'updatePlayerId']);
    //set user custom status route
    Route::post('set-user-status', [API\UserAPIController::class, 'setUserCustomStatus'])->name('set-user-status');
    Route::get('clear-user-status', [API\UserAPIController::class, 'clearUserCustomStatus'])->name('clear-user-status');

    //report user
    Route::post('report-user', [API\ReportUserController::class, 'store'])->name('report-user.store');
});

// users
Route::group(['middleware' => ['permission:manage_users', 'auth', 'user.activated']], function () {
    Route::resource('users', UserController::class);
    Route::post('users/{user}/active-de-active', [UserController::class, 'activeDeActiveUser'])
        ->name('active-de-active-user');
    Route::post('users/{user}/update', [UserController::class, 'update']);
    Route::delete('users/{user}/archive', [UserController::class, 'archiveUser']);
    Route::post('users/restore', [UserController::class, 'restoreUser']);
});

// roles
Route::group(['middleware' => ['permission:manage_roles', 'auth', 'user.activated']], function () {
    Route::resource('roles', RoleController::class);
    Route::post('roles/{role}/update', [RoleController::class, 'update'])->name('roles.update');
});

// settings
Route::group(['middleware' => ['permission:manage_settings', 'auth', 'user.activated']], function () {
    Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::post('settings', [SettingsController::class, 'update'])->name('settings.update');
});

// reported-users
Route::group(['middleware' => ['permission:manage_reported_users', 'auth', 'user.activated']], function () {
    Route::resource('reported-users', ReportUserController::class);
});

// meetings
Route::group(['middleware' => ['permission:manage_meetings', 'auth', 'user.activated']], function () {
    Route::resource('meetings', MeetingController::class);
    Route::get('meetings/{meeting}/change-status', [MeetingController::class, 'changeMeetingStatus']);
});

Route::group(['middleware' => ['permission:manage_meetings', 'auth', 'user.activated']], function () {
    Route::get('member/meetings', [MeetingController::class, 'showMemberMeetings'])->name('meetings.member_index');
});

Route::group(['middleware' => ['web']], function () {
    Route::get('login/{provider}', [\App\Http\Controllers\Auth\SocialAuthController::class, 'redirect']);
    Route::get('login/{provider}/callback', [\App\Http\Controllers\Auth\SocialAuthController::class, 'callback']);
});

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMeetingRequest;
use App\Models\User;
use App\Models\ZoomMeeting;
use App\Queries\MeetingDataTable;
use App\Repositories\MeetingRepository;
use Auth;
use DataTables;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Laracasts\Flash\Flash;

/**
 * Class MeetingController
 */
class MeetingController extends AppBaseController
{
    /**
     * @var MeetingRepository
     */
    private $meetingRepository;

    /**
     * MeetingController constructor.
     * @param  MeetingRepository  $meetingRepository
     */
    public function __construct(MeetingRepository $meetingRepository)
    {
        $this->meetingRepository = $meetingRepository;
    }

    /**
     * @param  Request  $request
     *
     * @throws Exception
     *
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return Datatables::of((new MeetingDataTable())->get())->make(true);
        }

        return view('meetings.index');
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        $timeZones = getTimeZone();
        $users = User::where('id', '!=', Auth::id())->pluck('name', 'id');

        return view('meetings.create', compact('users', 'timeZones'));
    }

    /**
     * @param int $meeting
     *
     * @return RedirectResponse
     */
    public function edit($meeting)
    {
        $timeZones = getTimeZone();
        $meeting = ZoomMeeting::with('members')->findOrFail($meeting);
        if ($meeting->status == ZoomMeeting::STATUS_FINISHED) {
            Flash::error('Sorry, Can not update finished meeting.');

            return redirect()->route('meetings.index');
        }

        $meetingTimeZone = array_flip($timeZones)[$meeting->time_zone];
        $members = $meeting->members->pluck('id')->toArray();
        $users = User::where('id', '!=', Auth::id())->pluck('name', 'id');

        return view('meetings.edit', compact('users', 'meeting', 'timeZones', 'members', 'meetingTimeZone'));
    }

    /**
     * @param  CreateMeetingRequest  $request
     *
     * @return RedirectResponse
     */
    public function store(CreateMeetingRequest $request)
    {


       // dd($request);
            $DATA=$this->meetingRepository->store($request->all());
            DD($DATA);
        Flash::success('Meeting saved successfully.');

        return redirect()->route('meetings.index');
    }

    /**
     * @param $meeting
     * @param  CreateMeetingRequest  $request
     *
     * @return RedirectResponse
     */
    public function update($meeting, CreateMeetingRequest $request)
    {
        $this->meetingRepository->updateZoomMeeting($meeting, $request->all());
        Flash::success('Meeting updated successfully.');

        return redirect()->route('meetings.index');
    }

    /**
     * @param  Request  $request
     *
     * @throws Exception
     *
     * @return Application|Factory|View
     */
    public function showMemberMeetings(Request $request)
    {
        if ($request->ajax()) {
            return Datatables::of((new MeetingDataTable())->get($member = true))->make(true);
        }

        return view('meetings.members_index');
    }

    /**
     * @param  ZoomMeeting  $meeting
     *
     * @return JsonResponse
     */
    public function destroy(ZoomMeeting $meeting)
    {
        $this->meetingRepository->deleteMeeting($meeting->id);

        return $this->sendSuccess('Meeting deleted successfully.');
    }

    /**
     * @param  ZoomMeeting  $meeting
     *
     * @return JsonResponse
     */
    public function changeMeetingStatus(ZoomMeeting $meeting)
    {
        $this->meetingRepository->changeMeetingStatus($meeting->id);

        return $this->sendSuccess('Meeting status updated successfully.');
    }
}

resources/views/meetings/create.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.new_meeting') }}
@endsection
@section('page_css')
@endsection
@section('css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="pull-left page__heading">
                                {{ __('messages.new_meeting') }}
                            </div>
                        </div>
                        <div class="card-body">
                            @include('coreui-templates::common.errors')
                            <form method="post" action="{{ route('meetings.store') }}">
                                {{ csrf_field() }}
                                <div class="row">
                                @include('meetings.fields')
                                </div>
                              
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_js')
@endsection
@section('scripts')
    <script src="{{ mix('assets/js/admin/meetings/meetings.js') }}"></script>
@endsection

resources/views/meetings/edit.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.edit_meeting') }}
@endsection
@section('page_css')
@endsection
@section('css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="pull-left page__heading">
                                {{ __('messages.edit_meeting') }}
                            </div>
                        </div>
                        <div class="card-body">
                            @include('coreui-templates::common.errors')
                                {{ Form::model($meeting, ['route' => ['meetings.update', $meeting->id], 'method' => 'put']) }}
                                {{ csrf_field() }}
                                <div class="row">
                                    @include('meetings.fields')
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_js')
@endsection
@section('scripts')
    <script src="{{ mix('assets/js/admin/meetings/meetings.js') }}"></script>
@endsection

resources/views/meetings/fields.blade.php
<div class="form-group col-sm-6">
    {!! Form::label('topic', __('messages.meeting.meeting_title').':' )!!}<span class="red">*</span>
    {!! Form::text('topic', isset($meeting) ? $meeting->topic : null, ['class' => 'form-control', 'required']) !!}
</div>

<div class="form-group col-sm-3 col-md-6 col-lg-6 col-xl-3">
    {!! Form::label('start_time', __('messages.meeting.meeting_date').':' )!!}<span class="red">*</span>
    {!! Form::text('start_time', isset($meeting) ? $meeting->start_time : null, ['class' => 'form-control start-time', 'required', 'autocomplete' => 'off']) !!}
</div>

<div class="form-group col-sm-6 col-md-6 col-lg-6 col-xl-3">
    {!! Form::label('time_zone', __('messages.meeting.time_zone').':' )!!}<span class="red">*</span>
    {!! Form::select('time_zone', $timeZones, isset($meetingTimeZone) ? $meetingTimeZone : null, ['class' => 'form-control time-zone', 'placeholder' => 'Select timezone', 'required' ]) !!}
</div>

<div class="form-group col-sm-6 col-md-6 col-lg-6 col-xl-3">
    {!! Form::label('duration', __('messages.meeting.meeting_duration').':')!!}<span class="red">*</span>
    {!! Form::number('duration', isset($meeting) ? $meeting->duration : null, ['class' => 'form-control', 'required']) !!}
</div>

<div class="form-group col-sm-6 col-md-6 col-lg-6 col-xl-3">
    {!! Form::label('members',__('messages.meeting.staff_list').':')!!}<span class="red">*</span>
    {!! Form::select('members[]', $users, isset($members) ? $members : null, ['class' => 'form-control members', 'multiple', 'required']) !!}
</div>

<div class="form-group col-sm-6 col-md-3 col-lg-6 col-xl-3">
    {!! Form::label('host_video',__('messages.meeting.host_video').':')!!}<span class="red">*</span>
    <div>
    {{ Form::radio('host_video', '1' , true) }}&nbsp{{__('messages.meeting.enabled')}}&nbsp;
    {{ Form::radio('host_video', '0' , false) }}&nbsp{{__('messages.meeting.disabled')}}&nbsp;
    </div>
</div>

<div class="form-group col-sm-6 col-md-3 col-lg-6 col-xl-3">
    {!! Form::label('participant_video',__('messages.meeting.client_video').':')!!}<span class="red">*</span>
    <div>
    {{ Form::radio('participant_video', '1' , true) }}&nbsp{{__('messages.meeting.enabled')}}&nbsp;
    {{ Form::radio('participant_video', '0' , false) }}&nbsp{{__('messages.meeting.disabled')}}&nbsp;
    </div>
</div>

<div class="form-group col-sm-12">
    {!! Form::label('agenda',__('messages.meeting.description').':')!!}<span class="red">*</span>
    {{ Form::textarea('agenda', null, ['class' => 'form-control', 'required']) }}
</div>

<div class="form-group col-sm-12">
    <a href="{{ route('meetings.index') }}"
            class="btn btn-secondary pull-right">{{ __('messages.cancel') }}</a>
    <button type="submit"
            class="btn btn-primary pull-right mr-1">{{ __('messages.save') }}</button>
</div>

resources/views/meetings/index.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.meetings') }}
@endsection
@section('page_css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/dataTable.min.css') }}"/>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container meetings-container">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header page-header">
                            <div class="pull-left page__heading">
                                {{ __('messages.meetings') }}
                            </div>
                            <div class="filter-container">
                                <a href="{{ route('meetings.create') }}" class="pull-right btn btn-primary">{{ __('messages.new_meeting') }}</a>
                            </div>
                        </div>
                        <div class="card-body">
                            @include('meetings.table')
                            <div class="pull-right mr-3">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_js')
    <script type="text/javascript" src="{{ asset('js/dataTable.min.js') }}"></script>
@endsection
@section('scripts')
    <script>
        let createMeetingUrl = "{{ route('meetings.store') }}";
        let meetingsUrl = "{{ route('meetings.index') }}";
        let defaultImageAvatar = "{{ getDefaultAvatar() }}/";
    </script>
    <script src="{{ mix('assets/js/admin/meetings/meetings.js') }}"></script>
    <script src="{{ mix('assets/js/admin/meetings/meeting_index.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/custom-datatables.js') }}"></script>
@endsection

resources/views/meetings/member_table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped table-bordered" id="memberMeetingTable">
        <thead>
        <th>{{ __('messages.topic') }}</th>
        <th>{{ __('messages.start_time') }}</th>
        <th>{{ __('messages.duration') }}</th>
        <th>{{ __('messages.status') }}</th>
        <th>{{ __('messages.password') }}</th>
        <th>{{ __('messages.join') }}</th>
        </thead>
        <tbody></tbody>
    </table>
</div>

resources/views/meetings/members_index.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.meetings') }}
@endsection
@section('page_css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/dataTable.min.css') }}"/>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header page-header">
                            <div class="pull-left page__heading">
                                {{ __('messages.meetings') }}
                            </div>
                        </div>
                        <div class="card-body">
                            @include('meetings.member_table')
                            <div class="pull-right mr-3">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_js')
    <script type="text/javascript" src="{{ asset('js/dataTable.min.js') }}"></script>
@endsection
@section('scripts')
    <script>
        let meetingsUrl = "{{ route('meetings.member_index') }}";
    </script>
    <script src="{{ mix('assets/js/admin/meetings/member_meeting_index.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/custom-datatables.js') }}"></script>
@endsection

resources/views/meetings/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped table-bordered" id="meetingsTable">
        <thead>
        <th>{{ __('messages.topic') }}</th>
        <th>{{ __('messages.start_time') }}</th>
        <th>{{ __('messages.duration') }}</th>
        <th>{{ __('messages.status') }}</th>
        <th>{{ __('messages.password') }}</th>
        <th>{{ __('messages.action') }}</th>
        </thead>
        <tbody></tbody>
    </table>
</div>